# Generated by Django 5.2.4 on 2025-07-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_from_founder",
                    models.TextField(verbose_name="Message from the Founder"),
                ),
                ("smart_learner", models.TextField(verbose_name="Smart Learner")),
                ("our_mission", models.TextField(verbose_name="Our Mission")),
                ("our_vision", models.TextField(verbose_name="Our Vision")),
                (
                    "why_smart_learner",
                    models.TextField(verbose_name="Why Smart Learner?"),
                ),
            ],
        ),
    ]
