# Generated by Django 5.2.4 on 2025-07-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PoliciesProcedures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrollment_policy",
                    models.TextField(verbose_name="Enrollment Policy"),
                ),
                (
                    "attendance_policy",
                    models.TextField(verbose_name="Attendance Policy"),
                ),
                (
                    "assessments_policy",
                    models.TextField(verbose_name="Assessments Policy"),
                ),
                ("code_of_conduct", models.TextField(verbose_name="Code of Conduct")),
                (
                    "cost_saving_benefits",
                    models.TextField(verbose_name="Cost-Saving Benefits"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="skillbasedECprograms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "programs_included",
                    models.TextField(verbose_name="Programs Included"),
                ),
                (
                    "program_highlights",
                    models.TextField(verbose_name="Program Highlights"),
                ),
            ],
        ),
    ]
