# Generated by Django 5.2.4 on 2025-07-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_policiesprocedures_skillbasedecprograms"),
    ]

    operations = [
        migrations.CreateModel(
            name="contactusForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent_name", models.CharField(verbose_name="Parent Name")),
                (
                    "student_first_name",
                    models.CharField(verbose_name="Student First Name"),
                ),
                (
                    "student_last_name",
                    models.CharField(verbose_name="Student Last Name"),
                ),
                ("email", models.CharField(verbose_name="Email")),
                ("phone", models.CharField(verbose_name="Phone")),
                ("country", models.CharField(verbose_name="Country")),
            ],
        ),
        migrations.CreateModel(
            name="registrationForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent_name", models.CharField(verbose_name="Parent Name")),
                (
                    "student_first_name",
                    models.CharField(verbose_name="Student First Name"),
                ),
                (
                    "student_last_name",
                    models.CharField(verbose_name="Student Last Name"),
                ),
                ("email", models.CharField(verbose_name="Email")),
                ("phone", models.CharField(verbose_name="Phone")),
                ("country", models.CharField(verbose_name="Country")),
                ("gender", models.CharField(verbose_name="Gender")),
                ("grade", models.IntegerField(verbose_name="Grade")),
                ("age", models.IntegerField(verbose_name="Age")),
                ("subject", models.CharField(verbose_name="Subject")),
            ],
        ),
    ]
