# Generated by Django 5.2.4 on 2025-07-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_contactusform_registrationform'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='free_education',
            field=models.TextField(default='', verbose_name='Every child deserves the chance to learn.'),
            preserve_default=False,
        ),
    ]
